name: mineslither
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  localstorage: ^4.0.0+1
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_analytics: ^10.0.7
  go_router: ^5.2.4
  flutter_donation_buttons: ^0.1.6
  flutter_colorpicker: ^1.0.3

msix_config:
  display_name: MineSlither
  publisher_display_name: MineSlither
  identity_name: com.mineslither
  msix_version: 1.0.0.0
  # logo_path: C:\path\to\logo.png
  capabilities: internetClient

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/0.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/bomb.png
    - assets/images/facingDown.png
    - assets/images/flagged.png
    - assets/images/bg.png