// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsp1fCM-ax3Qp8uj_Yl8CTLmO4zzcZnY0',
    appId: '1:833265131898:web:2f91eb1d30db728251b6c3',
    messagingSenderId: '833265131898',
    projectId: 'mineslither-61de5',
    authDomain: 'mineslither-61de5.firebaseapp.com',
    storageBucket: 'mineslither-61de5.appspot.com',
    measurementId: 'G-D6248D529E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8fWRg_lFjFsu_SlxWwSBQoEb_yjulnU',
    appId: '1:833265131898:android:fd9d72c4976103b951b6c3',
    messagingSenderId: '833265131898',
    projectId: 'mineslither-61de5',
    storageBucket: 'mineslither-61de5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuZx7IbCJqXWYTZqMxAHY4u_XcQblRhtk',
    appId: '1:833265131898:ios:74178a8036115e2f51b6c3',
    messagingSenderId: '833265131898',
    projectId: 'mineslither-61de5',
    storageBucket: 'mineslither-61de5.appspot.com',
    iosClientId:
        '833265131898-rs2j2nn6s176m3b18qtq3eonpi8skugo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mineslither',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuZx7IbCJqXWYTZqMxAHY4u_XcQblRhtk',
    appId: '1:833265131898:ios:74178a8036115e2f51b6c3',
    messagingSenderId: '833265131898',
    projectId: 'mineslither-61de5',
    storageBucket: 'mineslither-61de5.appspot.com',
    iosClientId:
        '833265131898-rs2j2nn6s176m3b18qtq3eonpi8skugo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mineslither',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuZx7IbCJqXWYTZqMxAHY4u_XcQblRhtk',
    appId: '1:833265131898:ios:74178a8036115e2f51b6c3',
    messagingSenderId: '833265131898',
    projectId: 'mineslither-61de5',
    storageBucket: 'mineslither-61de5.appspot.com',
  );
}
